teamColours = {
    "Alfa Romeo": "maroon",
    "AlphaTauri": "grey",
    "Alpine F1 Team": "blue",
    "Aston Martin": "green",
    "Red Bull": "navy",
    "Brawn": "chartreuse",
    "BAR": "whitesmoke",
    "BMW Sauber": "cornflowerblue",
    "BRM": "darkgreen",
    "Benetton": "skyblue",
    "Brabham": "darkblue",
    "Brabham-Repco": "green",
    "Caterham": "green",
    "Cooper-Castellotti": "green",
    "Cooper-Climax": "midnightblue",
    "Cooper-Maserati": "red",
    "Dallara": "red",
    "Epperly": "yellow",
    "Euro Brun": "orange",
    "Fittipaldi": "yellow",
    "Footwork": "whitesmoke",
    "Forti": "yellow",
    "Force India": "coral",
    "Ferrari": "red",
    "HRT": "whitesmoke",
    "Haas F1 Team": "whitesmoke",
    "Honda": "whitesmoke",
    "Jaguar": "green",
    "Jordan": "limegreen",
    "Larrousse": "navy",
    "Leyton House": "lightskyblue",
    "Ligier": "blue",
    "Lotus": "black",
    "Lotus F1": "black",
    "MF1": "red",
    "Manor Marussia": "orange",
    "Marussia": "red",
    "Maserati": "darkred",
    "McLaren": "orange",
    "McLaren-Alfa Romeo": "yellow",
    "McLaren-Ford": "whitesmoke",
    "Mercedes": "aqua",
    "Minardi": "yellow",
    "Renault": "yellow",
    "Racing Point": "hotpink",
    "Sauber": "crimson",
    "Spyker": "orange",
    "Spyker MF1": "orange",
    "Super Aguri": "whitesmoke",
    "Team Lotus": "green",
    "Toro Rosso": "midnightblue",
    "Toleman": "blue",
    "Toyota": "whitesmoke",
    "Tyrrell": "mediumblue",
    "Williams": "lightblue",
    "Virgin": "orange",
    "Gold": "gold",
    "Silver": "silver",
}
# Use this to build out list of colours
